english_spam: |
  #1	Free money	Online marketing
  $$$	Free offer	Online pharmacy
  100% free	Free preview	Only
  100% Satisfied	Free priority mail	Only $
  4U	Free quote	Order
  50% off	Free sample	Order today
  Accept credit cards	Free trial	Orders shipped by
  Acceptance	Free website	Outstanding values
  Access	Freedom	Passwords
  Accordingly	Friend	Pennies a day
  Act Now!	Full refund	Per day
  Act now! Don't hesitate!	Get	Per week
  Ad	Get It Now	Performance
  Additional income	Get it now	Phone
  Addresses on CD	Get out of debt	Please read
  Affordable	Get paid	Potential earnings
  All natural	Get started now	Pre-approved
  All new	Gift certificate	Price
  Amazing	Give it away	Print out and fax
  Apply now	Giving away	Priority mail
  Apply Online	Great offer	Prize
  As seen on	Guarantee	Prizes
  Auto email removal	Guaranteed	Problem
  Avoid	Have you been turned down?	Produced and sent out
  Avoid bankruptcy	Hello	Profits
  Bargain	Here	Promise you
  Be amazed	Hidden	Quote
  Be your own boss	Hidden assets	Refinance
  Being a member	Hidden charges	Refinance home
  Beneficiary	Home	Remove
  Best price	Home based	Reverses
  Beverage	Home employment	Reverses aging
  Big bucks	Homebased business	Risk free
  Bill 1618	Human growth hormone	Rolex
  Billing address	If only it were that easy	Round the world
  Billion	Important information regarding	S 1618
  Billion dollars	In accordance with laws	Safeguard notice
  Bonus	Income	Sale
  Brand new pager	Income from home	Sales
  Bulk email	Increase sales	Sample
  Buy	Increase traffic	Satisfaction
  Buy direct	Increase your sales	Satisfaction guaranteed
  Buying judgments	Incredible deal	Save $
  Cable converter	Info you requested	Save big money
  Call	Information you requested	Save up to
  Call free	Instant	Score with babes
  Call now	Insurance	Search engines
  Calling creditors	Internet market	Section 301
  Can't live without	Internet marketing	See for yourself
  Cancel at any time	Investment	Sent in compliance
  Cannot be combined with any other offer	Investment decision	Serious cash
  Cards accepted	It's effective	Serious only
  Cash	Join millions	Shopper
  Cash bonus	Join millions of Americans	Shopping spree
  Cashcashcash	Laser printer	Sign up free today
  Casino	Leave	Social security number
  Celebrity	Legal	Solution
  Cell phone cancer scam	Life	Special promotion
  Cents on the dollar	Lifetime	Stainless steel
  Certified	Limited time	Stock alert
  Chance	Limited time only	Stock disclaimer statement
  Cheap	Loans	Stock pick
  Check	Long distance phone offer	Stop
  Check or money order	Lose	Stop snoring
  Claims	Lose weight	Strong buy
  Claims not to be selling anything	Lose weight spam	Stuff on sale
  Claims to be in accordance with some spam law	Lower interest rate	Subject to credit
  Claims to be legal	Lower interest rates	Subscribe
  Clearance	Lower monthly payment	Success
  Click	Lower your mortgage rate	Supplies are limited
  Click here	Lowest insurance rates	Take action now
  Click to remove	Lowest price	Talks about hidden charges
  Collect	Luxury car	Talks about prizes
  Compare	Mail in order form	Teen
  Confidentially on all orders	Maintained	Tells you it's an ad
  Congratulations	Make $	Terms and conditions
  Consolidate debt and credit	Make money	The best rates
  Consolidate your debt	Marketing	The following form
  Copy accurately	Marketing solutions	They keep your money -- no refund!
  Copy DVDs	Mass email	They keep your money!!! no refund!
  Cost	Medicine	They're just giving it away
  Costs	Medium	They're just giving it away
  Credit	Meet singles	This isn't junk
  Credit bureaus	Member	This isn't spam
  Credit card offers	Member stuff	This won't last
  Cures baldness	Message contains	 This isn't a scam
  Deal	Message contains disclaimer	Thousands
  Dear [email/friend/somebody]	Million	Time limited
  Diagnostics	Million dollars	Trial
  Dig up dirt on friends	Miracle	Undisclosed recipient
  Direct email	MLM	University diplomas
  Direct marketing	Money	Unlimited
  Discount	Money back	Unsecured credit
  Do it today	Money making	Unsecured credit/debt
  Don't delete	Month trial offer	Unsecured debt
  Don't hesitate	More Internet traffic	Unsolicited
  Dormant	Mortgage	Unsubscribe
  Double your	Mortgage rates	Urgent
  Drastically reduced	Multi level marketing	US dollars
  Earn	Name brand	Vacation
  Earn $	Never	Vacation offers
  Earn extra cash	New customers only	Valium
  Earn per week	New domain extensions	Viagra
  Easy terms	Nigerian	Viagra and other drugs
  Eliminate bad credit	No age restrictions	Vicodin
  Eliminate debt	No catch	Visit our website
  Email harvest	No claim forms	Wants credit card
  Email marketing	No cost	Warranty
  Expect to earn	No credit check	We hate spam
  Explode your business	No disappointment	We honor all
  Extra income	No experience	Web traffic
  Free	No fees	Weekend getaway
  Fantastic deal	No gimmick	Weight loss
  Fast cash	No hidden	What are you waiting for?
  Financial freedom	No inventory	While supplies last
  Financially independent	No investment	While you sleep
  For free	No medical exams	Who really wins?
  For instant access	No middleman	Why pay more?
  For just $ (some amt)	No obligation	Wife
  For just $XXX	No purchase necessary	Will not believe your eyes
  For Only	No-obligation	Win
  For you	Not intended	Winner
  Form	Notspam	Winning
  Free	Now	Won
  Free access	Now only	Work at home
  Free cell phone	Obligation	Work from home
  Free consultation	Offer	Xanax
  Free DVD	Offer expires	You are a winner!
  Free gift	Once in lifetime	You have been selected
  Free grant money	One hundred percent free	You're a Winner!
  Free hosting	One hundred percent guaranteed	Your income
  Free installation	One time
  Free Instant	One time mailing
  Free investment	Online degree
  Free leads	Open
  Free membership	Opportunity
  4U	Claims you are a winner	For instant access
  Accept credit cards	Claims you registered with Some Kind of Partner	For just $ (some amt)
  Act now! Don’t hesitate!	Click below	Free access
  Additional income	Click here link	Free cell phone
  Addresses on CD	Click to remove	Free consultation
  All natural	Click to remove mailto	Free DVD
  Amazing	Compare rates	Free grant money
  Apply Online	Compete for your business	Free hosting
  As seen on	Confidentially on all orders	Free installation
  Auto email removal	Congratulations	Free investment
  Avoid bankruptcy	Consolidate debt and credit	Free leads
  Be amazed	Copy accurately	Free membership
  Be your own boss	Copy DVDs	Free money
  Being a member	Credit bureaus	Free offer
  Big bucks	Credit card offers	Free preview
  Bill 1618	Cures baldness	Free priority mail
  Billing address	Dear email	Free quote
  Billion dollars	Dear friend	Free sample
  Brand new pager	Dear somebody	Free trial
  Bulk email	Different reply to	Free website
  Buy direct	Dig up dirt on friends	Full refund
  Buying judgments	Direct email	Get It Now
  Cable converter	Direct marketing	Get paid
  Call free	Discusses search engine listings	Get started now
  Call now	Do it today	Gift certificate
  Calling creditors	Don’t delete	Great offer
  Can’t live without	Drastically reduced	Guarantee
  Cancel at any time	Earn per week	Have you been turned down?
  Cannot be combined with any other offer	Easy terms	Hidden assets
  Cash bonus	Eliminate bad credit	Home employment
  Cashcashcash	Email harvest	Human growth hormone
  Casino	Email marketing	If only it were that easy
  Cell phone cancer scam	Expect to earn	In accordance with laws
  Cents on the dollar	Fantastic deal	Increase sales
  Check or money order	Fast Viagra delivery	Increase traffic
  Claims not to be selling anything	Financial freedom	Insurance
  Claims to be in accordance with some spam law	Find out anything	Investment decision
  Claims to be legal	For free	It's effective
  Join millions of Americans	No questions asked	Reverses aging
  Laser printer	No selling	Risk free
  Limited time only	No strings attached	Round the world
  Long distance phone offer	Not intended	S 1618
  Lose weight spam	Off shore	Safeguard notice
  Lower interest rates	Offer expires	Satisfaction guaranteed
  Lower monthly payment	Offers coupon	Save $
  Lowest price	Offers extra cash	Save big money
  Luxury car	Offers free (often stolen) passwords	Save up to
  Mail in order form	Once in lifetime	Score with babes
  Marketing solutions	One hundred percent free	Section 301
  Mass email	One hundred percent guaranteed	See for yourself
  Meet singles	One time mailing	Sent in compliance
  Member stuff	Online biz opportunity	Serious cash
  Message contains disclaimer	Online pharmacy	Serious only
  MLM	Only $	Shopping spree
  Money back	Opportunity	Sign up free today
  Money making	Opt in	Social security number
  Month trial offer	Order now	Special promotion
  More Internet traffic	Order status	Stainless steel
  Mortgage rates	Orders shipped by priority mail	Stock alert
  Multi level marketing	Outstanding values	Stock disclaimer statement
  Name brand	Pennies a day	Stock pick
  New customers only	People just leave money laying around	Stop snoring
  New domain extensions	Please read	Strong buy
  Nigerian	Potential earnings	Stuff on sale
  No age restrictions	Print form signature	Subject to credit
  No catch	Print out and fax	Supplies are limited
  No claim forms	Produced and sent out	Take action now
  No cost	Profits	Talks about hidden charges
  No credit check	Promise you …!	Talks about prizes
  No disappointment	Pure profit	Tells you it’s an ad
  No experience	Real thing	Terms and conditions
  No fees	Refinance home	The best rates
  No gimmick	Removal instructions	The following form
  No inventory	Remove in quotes	They keep your money — no refund!
  No investment	Remove subject	They’re just giving it away
  No medical exams	Removes wrinkles	This isn’t junk
  No middleman	Reply remove subject	This isn’t spam
  No obligation	Requires initial investment	University diplomas
  No purchase necessary	Reserves the right	Unlimited
  Unsecured credit/debt	We honor all	Will not believe your eyes
  Urgent	Weekend getaway	Winner
  US dollars	What are you waiting for?	Winning
  Vacation offers	While supplies last	Work at home
  Viagra and other drugs	While you sleep	You have been selected
  Wants credit card	Who really wins?	Your income
  We hate spam	Why pay more?